### ISSUE TITLE
Error at wrong username when logging in

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/ZapServer#8]
When entering wrong email address in Login api call, this is returned
`{"status":500,"error":"Internal Server Error"}`

Should be changed to 422(or related) with a relevant error message.

- Example
`curl -k -v -H "Content-Type:application/json" -d '{"session":{"password":"123456789","email":"example@zapserver1.com"}}' https://zapserver.herokuapp.com/api/sessions/`

**Comment by DevArenaCN** [comment]
Working on this right now. Tried several methods, still 500 error, I think it's due to Rails ActiveRecord, when a record is not found, it's gonna render a 500 error, try to override this by using some sort of catch exception but it's not functional somehow. Just use the 500 error for now, I'll work on something later

**Comment by thegreyd** [comment]
This is fixed now. Getting the right error message.
